{
 "title": "Fruits Grocery User0",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Fruits inventory invocations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{app=\"fruits-inventory\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "Fruits inventory invocations "
    }
   ]
  },
  {
   "title": "Fruits Catalog invocations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=\"fruits-catalog\",exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}"
    }
   ]
  },
  {
   "title": "Fruits Inventory Response times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{app=\"fruits-inventory\",le=\"1.5\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{app=\"fruits-inventory\",le=\"0.3\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{app=\"fruits-inventory\",le=\"0.1\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{app=\"fruits-inventory\",le=\"0.03\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "less than {{le}}"
    },
    {
     "expr": "http_request_duration_seconds_bucket{app=\"fruits-inventory\",le=\"0.003\",status_code=\"200\",method=\"GET\",path=\"/api/fruits\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "less than {{le}}"
    }
   ]
  },
  {
   "title": "Fruits Catalog Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{app=\"fruits-catalog\",uri=\"/api/fruits\",status=\"200\",kubernetes_namespace=\"fruits-grocery-dev-user0\"} / http_server_requests_seconds_count{app=\"fruits-catalog\",uri=\"/api/fruits\",status=\"200\",kubernetes_namespace=\"fruits-grocery-dev-user0\"}",
     "legendFormat": "Mean response time"
    }
   ]
  },
  {
   "title": "Fruits Catalog JVM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"fruits-catalog\",kubernetes_namespace=\"fruits-grocery-dev-user0\",area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}